<?php
/**
 * @file
 * Bibliotek.dk search carousel module main file.
 */

/**
 * Implements hook_menu().
 */
function bibdk_search_carousel_menu() {
  $items = array();
  $items['admin/config/ting/ting_search_carousel/bibdk_settings'] = array(
    'title' => 'Bibliotek.dk settings',
    'description' => 'Manage Bibliotek.dk settings for the search webservice',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('bibdk_search_carousel_admin_form'),
    'access arguments' => array('access administration pages'),
    'file' => 'bibdk_search_carousel.admin.inc',
    'type' => MENU_LOCAL_TASK,
    'weight' => 0,
  );
  return $items;
}


/**
 * Implements hook_menu().
 */
function bibdk_search_carousel_form_ting_search_carousel_admin_form_alter(&$form, &$form_state, $form_id) {

  drupal_add_css(drupal_get_path('module', 'bibdk_search_carousel') . '/bibdk_search_carousel.css');

  // Get current saved queries.
  $searches = variable_get('ting_carousel_search_queries', array());

  $frequency = array(
    '#title' => t('Frequency'),
    '#type' => 'select',
    '#options' => array(
      0 => t('Static'),
      1 => t('1 week'),
      2 => t('2 weeks'),
      3 => t('3 weeks'),
      4 => t('4 weeks'),
    ),
    '#description' => t('Select frequency for this carousel search.'),
  );

  $period = array(
    '#title' => t('Period'),
    '#type' => 'select',
    '#options' => array(
      0 => t('All'),
      1 => t('1 week'),
      2 => t('2 weeks'),
      3 => t('3 weeks'),
      4 => t('4 weeks'),
      5 => t('5 weeks'),
      6 => t('6 weeks'),
      7 => t('7 weeks'),
      8 => t('8 weeks'),
      9 => t('9 weeks'),
      10 => t('10 weeks'),
      11 => t('11 weeks'),
      12 => t('12 weeks'),
    ),
    '#default_value' => isset($item['period']) ? $item['period'] : '',
    '#description' => t('Select Period for this carousel search.'),
  );

  $offset = array(
    '#title' => t('Offset'),
    '#type' => 'select',
    '#options' => array(
      0 => t('None'),
      1 => t('1 week'),
      2 => t('2 weeks'),
      3 => t('3 weeks'),
      4 => t('4 weeks'),
      5 => t('5 weeks'),
      6 => t('6 weeks'),
      7 => t('7 weeks'),
      8 => t('8 weeks'),
      9 => t('9 weeks'),
      10 => t('10 weeks'),
      11 => t('11 weeks'),
      12 => t('12 weeks'),
    ),
    '#default_value' => isset($item['offset']) ? $item['offset'] : '',
    '#description' => t('Select offset for this carousel search.'),
  );

  $searches_num = sizeof($form['ting_search_carousel']['ting_searches']);
  for ($i = 0; $i < $searches_num; $i++) {
    $form['ting_search_carousel']['ting_searches']['search_' . $i]['bibdk_search_carousel'] = array(
      '#type' => 'fieldset',
      '#title' => t('Search settings'),
      '#title_display' => 'invisible',
    );
    $frequency['#default_value'] = isset($searches[$i]['frequency']) ? $searches[$i]['frequency'] : '';
    $period['#default_value']    = isset($searches[$i]['period'])    ? $searches[$i]['period']    : '';
    $offset['#default_value']    = isset($searches[$i]['offset'])    ? $searches[$i]['offset']    : '';

    $form['ting_search_carousel']['ting_searches']['search_' . $i]['bibdk_search_carousel']['frequency[]']  = $frequency;
    $form['ting_search_carousel']['ting_searches']['search_' . $i]['bibdk_search_carousel']['period[]']     = $period;
    $form['ting_search_carousel']['ting_searches']['search_' . $i]['bibdk_search_carousel']['offset[]']     = $offset;

    $form['ting_search_carousel']['ting_searches']['search_' . $i]['remove[]']['#suffix'] = '';
  }

  // Custom form submit handler.
  $form['#submit'] = array('bibdk_search_carousel_search_submit');

}


/**
 * Submit handler for admin backend queries form.
 *
 * @param $form
 *   Form.
 * @param $form_state
 *   Form state.
 */
function bibdk_search_carousel_search_submit($form, &$form_state) {
  $c = count($form_state['input']['title']);
  $searches = array();
  $search_items = array();

  for ($i = 0; $i < $c; $i++) {
    // Make an array for saving, ignoring queries w/o title.
    if (!empty($form_state['input']['title'][$i])) {
      $searches[] = array(
        'title' => $form_state['input']['title'][$i],
        'subtitle' => $form_state['input']['subtitle'][$i],
        'query' => $form_state['input']['query'][$i],
        'frequency' => $form_state['input']['frequency'][$i],
        'period' => $form_state['input']['period'][$i],
        'offset' => $form_state['input']['offset'][$i]
      );
    }
  }

  /**
   * @TODO: Add clear cache button and detect changes in the query input fields
   * so only partial cache can be rebuild. This will slow down the submit but
   * may speed up the presentation for the users by kick starting the cache.
   */

  // Save the queries as a persistent variable.
  variable_set('ting_carousel_search_queries', $searches);

  // Clear carousel search cache
  cache_clear_all('ting_search_carousel_result', 'cache');
}


/**
 * Implements hook_ting_search_carousel_query().
 */
function bibdk_search_carousel_ting_search_carousel_query($query) {

  $bibdk_query_prefix = ' ' . t('BOOLEAN_AND') . ' ' .  variable_get('bibdk_search_carousel_week_search_code', 'dkcclterm.kk') . '=(';
  $bibdk_query_suffix = ')';
  $bibdk_dateformat = variable_get('bibdk_search_carousel_dateformat', 'bk\mYW');
  $today = time();
  $week = 7 * 24 * 60 * 60; // 7 days; 24 hours; 60 mins; 60secs

  $periods = array();
  for ($n = 0; $n < $query['period']; $n++) {
    $offset = $query['offset'];
    $weeks = $week * ( $n + $offset );
    $periods[] = date($bibdk_dateformat, $today - $weeks);
  }
  if ( !empty($periods)  ) {
    $query['query'] = $query['query'] . $bibdk_query_prefix . implode(' ' . t('BOOLEAN_OR') . ' ', $periods) . $bibdk_query_suffix;
  }

  return $query;
}



/**
 * Boolean operators have to be translated.
 */
t('BOOLEAN_AND');
t('BOOLEAN_OR');
t('BOOLEAN_NOT');
